# Generated by Django 3.0.8 on 2020-07-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='has_definite_end_date',
            field=models.BooleanField(default=True),
        ),
    ]
