# Generated by Django 3.0.8 on 2020-07-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200704_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='has_definite_end_date',
            new_name='has_definite_start_date',
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.Section'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
