# Generated by Django 3.0.8 on 2020-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_customuser_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='anonymous', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(max_length=2048, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
